### ISSUE TITLE
05.01 수정 필요한 부분

### ISSUE THREAD

**Issue by kimgorok** [SurBear-Team/surbear-server#26]
1. (POST) 설문 수정
deleted된 질문이 계속 보이는 문제
2. (POST) 설문 수정
deleted된 답변이 계속 보이는 문제
3. (POST) 설문 수정
질문의 제목만 변경할 경우, options의 afterChangeSurveyQuestionOptionList의 answer 내용을 보낼 게 없음.
before처럼 비워져 있었으면 함

**Comment by seorang42** [comment]
4. /member/survey/history를 통해서 받은 설문조사 목록과 /member/profile/counting/participation 개수가 불일치함
=> deleted가 반영이 안된 숫자가 반환되고 있지 않나 의심스러움

+ /survey/management/list와 /member/profile/counting/survey도 마찬가지로 개수가 불일치

**Comment by seorang42** [comment]
> 4. /member/survey/history를 통해서 받은 설문조사 목록과 /member/profile/counting/participation 개수가 불일치함
>    => deleted가 반영이 안된 숫자가 반환되고 있지 않나 의심스러움

DB 확인 결과 사라진 설문(예를 들어 survey_id : 1)에 대한 답변까지 개수에 포함시키고 있음

**Comment by jickDo** [comment]
> 1. (POST) 설문 수정
>    deleted된 질문이 계속 보이는 문제
> 2. (POST) 설문 수정
>    deleted된 답변이 계속 보이는 문제
> 3. (POST) 설문 수정
>    질문의 제목만 변경할 경우, options의 afterChangeSurveyQuestionOptionList의 answer 내용을 보낼 게 없음.
>    before처럼 비워져 있었으면 함

1. 내설문 단일 설문 조회 현제 삭제된것은 반환안되게 변경
2. 1번 2번, 3번 문제 해결

**Comment by jickDo** [comment]
> 4. /member/survey/history를 통해서 받은 설문조사 목록과 /member/profile/counting/participation 개수가 불일치함
>    => deleted가 반영이 안된 숫자가 반환되고 있지 않나 의심스러움
> 
> * /survey/management/list와 /member/profile/counting/survey도 마찬가지로 개수가 불일치

첫번째 문제같은 경우 기존 soft delete 로 삭제된 것들의 히스토리를 추적하고 결과를 리턴하였는데, 특정 컬럼이 하드딜리트 되어있는 문제가 있었습니다. 디비에 직접접근해서 지워진 로우값은 추적이 안되어서 생긴 문제인것으로 판단되며, 이런경우 기능적은 문제는 아니라고 판단됩니다
