### ISSUE TITLE
05.13

### ISSUE THREAD

**Issue by kimgorok** [SurBear-Team/surbear-server#44]
설문 종료일이 지난 설문이 ongoingType = CLOSE 로 변경 되게 수정 필요

**Comment by seorang42** [comment]
포인트 지급 내역(/point)에 updatedAt으로 null값이 넘어옴

설문 답변이 완료되었을 때 사용자에게 포인트가 지급되어야 함 - 해결 완료

관리자 기능 중 설문조사 강제 삭제 내역(/deletion/list)과 회원 설문조사 내역(role/participation)에서 삭제, 강제삭제된 기록이 넘어오지 않음

유저 답변 저장(/survey/answer/{surveyAnswerId}) 500 에러 - 해결 완료

**Comment by jickDo** [comment]
> 설문 종료일이 지난 설문이 ongoingType = CLOSE 로 변경 되게 수정 필요

해결했습니다

**Comment by jickDo** [comment]
> 포인트 지급 내역(/point)에 updatedAt으로 null값이 넘어옴
> 
> 설문 답변이 완료되었을 때 사용자에게 포인트가 지급되어야 함 - 해결 완료
> 
> 관리자 기능 중 설문조사 강제 삭제 내역(/deletion/list)과 회원 설문조사 내역(role/participation)에서 삭제, 강제삭제된 기록이 넘어오지 않음
> 
> 유저 답변 저장(/survey/answer/{surveyAnswerId}) 500 에러 - 해결 완료

해결했습니다 한번 확인해주세요
